package git_diff_parser

// ApplyMode controls how the apply engine treats hunks that cannot be placed
// directly into the target content.
type ApplyMode int

const (
	// ApplyModeApply keeps the output neutral when a hunk cannot be applied.
	ApplyModeApply ApplyMode = iota
	// ApplyModeMerge renders conflict markers into the output for misses.
	ApplyModeMerge
)

// ConflictLabels controls the labels rendered into conflict markers.
// The zero value renders neutral markers without any labels.
type ConflictLabels struct {
	Current  string
	Incoming string
}

// ApplyOptions configures the apply engine.
type ApplyOptions struct {
	Mode             ApplyMode
	ConflictLabels   ConflictLabels
	IgnoreWhitespace bool
	Reverse          bool
	UnidiffZero      bool
	Recount          bool
	InaccurateEOF    bool
}

func DefaultApplyOptions() ApplyOptions {
	return ApplyOptions{
		Mode: ApplyModeMerge,
		ConflictLabels: ConflictLabels{
			Current:  "Current",
			Incoming: "Incoming patch",
		},
	}
}

// PatchApply holds apply-time configuration and mirrors Git's stateful apply design.
type PatchApply struct {
	options ApplyOptions
}

func NewPatchApply(options ApplyOptions) *PatchApply {
	return &PatchApply{options: normalizeApplyOptions(options)}
}

func legacyApplyOptions() ApplyOptions {
	return ApplyOptions{
		Mode: ApplyModeMerge,
		ConflictLabels: ConflictLabels{
			Current:  "Current (Your changes)",
			Incoming: "New (Generated by Speakeasy)",
		},
	}
}

func (o ApplyOptions) normalize() ApplyOptions {
	if o.Mode != ApplyModeMerge {
		o.Mode = ApplyModeApply
	}
	if o.Mode == ApplyModeMerge {
		defaults := DefaultApplyOptions()
		if o.ConflictLabels.Current == "" {
			o.ConflictLabels.Current = defaults.ConflictLabels.Current
		}
		if o.ConflictLabels.Incoming == "" {
			o.ConflictLabels.Incoming = defaults.ConflictLabels.Incoming
		}
	}
	return o
}

func normalizeApplyOptions(options ApplyOptions) ApplyOptions {
	return options.normalize()
}
