name: lint

on:
  push:
    branches:
      - main
  pull_request:
env:
  GOPRIVATE: "github.com/speakeasy-api"
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Configure git for private modules
        env:
          GIT_AUTH_TOKEN: ${{ secrets.BOT_REPO_TOKEN }}
        run: git config --global url."https://speakeasybot:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"

      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.57.2
